#!/usr/bin/env python3
"""Opening-distribution-aligned PUCT replay ablation.

The only lane treatment is ``start_state_mode``.  In particular, replay is
generated by :func:`self_play.run_self_play_worker`, rather than by a second
implementation of PUCT or target construction.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

import numpy as np
import torch

REPO_ROOT = Path(__file__).resolve().parents[2]
if __package__ in (None, ""):
    sys.path.append(str(REPO_ROOT))

from ml.alphazero_lite.build_opening_suite import (  # noqa: E402
    canonical_key,
    deduplicate_openings,
    enumerate_legal_prefixes,
    select_diverse,
    stratify_openings,
)
from ml.alphazero_lite.run_deterministic_joint_heads_iteration import (  # noqa: E402
    build_manifest,
    compare_runs,
    game_split,
    train_fixed_manifest,
    value_change_metrics,
    value_metrics,
)
from ml.alphazero_lite.run_current_init_policy_only_distillation_preflight import (  # noqa: E402
    evaluate_policy_probe_metrics,
    evaluate_raw_outputs,
)
from ml.alphazero_lite.run_terminal_outcome_selfplay_iteration_smoke import (  # noqa: E402
    build_search_probe_rows,
    evaluate_search_outputs,
    evaluate_search_probe_metrics,
)
from ml.alphazero_lite.run_control_ep2_puct_head_preflight import (  # noqa: E402
    benchmark_budget_results,
    bootstrap_ci,
    find_candidate_report,
    pooled_per_opening_differences,
    run_opening_suite_benchmark,
)
from ml.alphazero_lite.cpuct_schedule import parse_cpuct_schedule_json  # noqa: E402
from ml.alphazero_lite.evaluation_seed_contract import SEED_CONTRACT_VERSION  # noqa: E402
from ml.alphazero_lite.self_play import (  # noqa: E402
    PRESET_POOL_START_STATE_MODE,
    STANDARD_START_STATE_MODE,
    run_self_play_worker,
    standard_start_state,
)

EXPECTED_CURRENT_SHA256 = (
    "8d70e90a684caf946ab3f3e5d81a24e65be939b5be932930c389945fd9bb4e7a"
)
SCHEMA = "azlite_distribution_aligned_selfplay_v1"
CORPUS_SIZE = 2048
OPENING_PLIES = (2, 4, 6)
DEFAULT_WORKDIR = Path("/tmp/azlite_distribution_aligned_selfplay")


class CorpusPreflightError(RuntimeError):
    """A required corpus stratum cannot satisfy the frozen exclusions."""

    def __init__(self, manifest: dict[str, Any], reason: str):
        super().__init__(reason)
        self.manifest = manifest
        self.reason = reason


def sha256_file(path: Path) -> str:
    """Return a content digest."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(65536), b""):
            digest.update(block)
    return digest.hexdigest()


def write_json(path: Path, payload: dict[str, Any]) -> None:
    """Write stable, reviewable JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    """Read JSONL records in their persisted order."""
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    """Write compact JSONL records."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, sort_keys=True) + "\n")


def suite_identities(
    paths: list[Path],
) -> tuple[set[str], set[tuple[int, ...]], dict[str, str]]:
    """Return exact state/prefix exclusions and input hashes for frozen suites."""
    states: set[str] = set()
    prefixes: set[tuple[int, ...]] = set()
    hashes: dict[str, str] = {}
    for path in paths:
        rows = read_jsonl(path)
        hashes[str(path)] = sha256_file(path)
        for row in rows:
            states.add(canonical_key(row["state"]))
            prefixes.add(tuple(int(move) for move in row.get("prefix_moves", [])))
            for alternate in row.get("alternate_prefixes", []):
                prefixes.add(tuple(int(move) for move in alternate))
    return states, prefixes, hashes


def build_training_opening_corpus(
    *,
    out_dir: Path,
    exclusion_suites: list[Path],
    seed: int,
    target_size: int = CORPUS_SIZE,
) -> tuple[Path, dict[str, Any]]:
    """Build a stratified, exact-disjoint corpus using evaluation's prefix generator."""
    excluded_states, excluded_prefixes, exclusion_hashes = suite_identities(
        exclusion_suites
    )
    prefixes = [
        entry
        for depth in OPENING_PLIES
        for entry in enumerate_legal_prefixes(depth)
        if entry["ply"] == depth
    ]
    unique, _duplicates, duplicate_count = deduplicate_openings(prefixes)
    eligible = [
        entry
        for entry in stratify_openings(unique)
        if canonical_key(entry["state"]) not in excluded_states
        and tuple(entry["prefix_moves"]) not in excluded_prefixes
        and not any(
            tuple(prefix) in excluded_prefixes
            for prefix in entry.get("alternate_prefixes", [])
        )
    ]
    if len(eligible) < target_size:
        raise RuntimeError(
            f"only {len(eligible)} disjoint starts available; need {target_size}"
        )
    selected = select_diverse(eligible, target_size, seed)
    # ``select_diverse`` intentionally stops when a bucket quota is exhausted.
    # Fill any residual budget from the same eligible population, retaining its
    # deterministic RNG and never weakening the exclusion contract.
    selected_hashes = {canonical_key(entry["state"]) for entry in selected}
    remainder = [
        entry
        for entry in eligible
        if canonical_key(entry["state"]) not in selected_hashes
    ]
    rng = random.Random(seed)
    rng.shuffle(remainder)
    selected.extend(remainder[: max(0, target_size - len(selected))])
    records = [
        {
            "state": entry["state"],
            "metadata": {
                "prefix_moves": entry["prefix_moves"],
                "opening_ply": entry["ply"],
                "phase": entry["phase_bucket"],
                "side_to_move": entry["side_to_move"],
            },
        }
        for entry in selected
    ]
    corpus_path = out_dir / "training_opening_corpus.jsonl"
    write_jsonl(corpus_path, records)
    hashes = [canonical_key(record["state"]) for record in records]
    manifest = {
        "schema": "training_opening_corpus_v1",
        "generator_version": "build_opening_suite_v1",
        "generator_seed": seed,
        "state_count": len(records),
        "prefix_depth_distribution": dict(
            sorted(
                Counter(record["metadata"]["opening_ply"] for record in records).items()
            )
        ),
        "player_to_move_distribution": dict(
            sorted(
                Counter(record["state"]["current_player"] for record in records).items()
            )
        ),
        "phase_distribution": dict(
            sorted(Counter(record["metadata"]["phase"] for record in records).items())
        ),
        "exact_state_hashes": hashes,
        "corpus_sha256": sha256_file(corpus_path),
        "exclusion_suite_hashes": exclusion_hashes,
        "exact_overlap_counts": {
            "states": len(set(hashes) & excluded_states),
            "prefixes": sum(
                tuple(r["metadata"]["prefix_moves"]) in excluded_prefixes
                for r in records
            ),
        },
        "duplicate_counts": {
            "enumeration": duplicate_count,
            "corpus_states": len(hashes) - len(set(hashes)),
        },
    }
    if (
        len(hashes) != target_size
        or len(set(hashes)) != target_size
        or any(manifest["exact_overlap_counts"].values())
    ):
        raise RuntimeError(
            "training opening corpus failed uniqueness or exclusion audit: "
            f"rows={len(hashes)} unique={len(set(hashes))} "
            f"overlap={manifest['exact_overlap_counts']}"
        )
    write_json(out_dir / "training_opening_corpus_manifest.json", manifest)
    missing_depths = sorted(
        set(OPENING_PLIES) - set(manifest["prefix_depth_distribution"])
    )
    if missing_depths or len(manifest["player_to_move_distribution"]) != 2:
        details = []
        if missing_depths:
            details.append(f"missing required opening depths: {missing_depths}")
        if len(manifest["player_to_move_distribution"]) != 2:
            details.append("both players are not represented")
        raise CorpusPreflightError(manifest, "; ".join(details))
    return corpus_path, manifest


def _decoded_state(row: dict[str, Any]) -> dict[str, Any]:
    values = row["state"]
    return {
        "player_pits": [round(v * 48) for v in values[:6]],
        "opponent_pits": [round(v * 48) for v in values[6:12]],
        "player_store": round(values[12] * 48),
        "opponent_store": round(values[13] * 48),
        "current_player": round(values[14]),
    }


def _phase(state: dict[str, Any]) -> str:
    stones = sum(state["player_pits"]) + sum(state["opponent_pits"])
    return "opening" if stones > 24 else "midgame" if stones > 12 else "late"


def replay_manifest(
    rows: list[dict[str, Any]], path: Path, *, lane: str, start_source: str, seed: int
) -> dict[str, Any]:
    """Summarize persisted replay without altering target semantics."""
    states = [_decoded_state(row) for row in rows]
    policies = [row["policy"] for row in rows]
    entropies = [
        -sum(p * math.log(p, 2) for p in policy if p > 0) for policy in policies
    ]
    return {
        "lane": lane,
        "replay_sha256": sha256_file(path),
        "row_count": len(rows),
        "game_count": len({int(row["game_index"]) for row in rows}),
        "unique_state_count": len({canonical_key(state) for state in states}),
        "start_state_source": start_source,
        "start_state_hashes": sorted(
            {
                str(row.get("start_state_hash", canonical_key(standard_start_state())))
                for row in rows
            }
        ),
        "player_distribution": dict(
            sorted(Counter(str(row["player"]) for row in rows).items())
        ),
        "phase_distribution": dict(
            sorted(Counter(_phase(state) for state in states).items())
        ),
        "policy_entropy": {"mean": float(np.mean(entropies)) if entropies else 0.0},
        "terminal_target_distribution": dict(
            sorted(Counter(str(row["value"]) for row in rows).items())
        ),
        "random_seeds": {"base_seed": seed},
    }


def generate_lane(
    *,
    lane: str,
    workdir: Path,
    checkpoint: Path,
    corpus: Path | None,
    target_rows: int,
    seed: int,
    simulations: int,
) -> tuple[Path, list[dict[str, Any]], dict[str, Any]]:
    """Generate whole games until the requested row budget is reached."""
    rows: list[dict[str, Any]] = []
    game_index = 0
    while len(rows) < target_rows:
        shard = workdir / f"{lane}_{game_index}.jsonl"
        result = run_self_play_worker(
            worker_id=0,
            start_index=game_index,
            games=32,
            seed=seed,
            seed_pool=[seed],
            checkpoint=str(checkpoint),
            input_encoding="kalah_v3",
            simulations=simulations,
            c_puct=1.25,
            temperature_threshold=8,
            temperature=0.67,
            temperature_late=0.0,
            dirichlet_alpha=0.3,
            dirichlet_epsilon=0.25,
            max_moves=200,
            shard_path=str(shard),
            root_policy_mode="visit_count",
            write_game_metadata=True,
            write_root_target_telemetry=True,
            start_state_mode=PRESET_POOL_START_STATE_MODE
            if corpus
            else STANDARD_START_STATE_MODE,
            start_state_pool_path=None if corpus is None else str(corpus),
        )
        del result
        rows.extend(read_jsonl(shard))
        game_index += 32
    by_game: dict[int, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        by_game[int(row["game_index"])].append(row)
    kept: list[dict[str, Any]] = []
    for index in sorted(by_game):
        if len(kept) + len(by_game[index]) > target_rows:
            break
        kept.extend(by_game[index])
    path = workdir / (
        "replay_standard.jsonl"
        if lane == "standard_start_control"
        else "replay_opening_seeded.jsonl"
    )
    write_jsonl(path, kept)
    manifest = replay_manifest(
        kept,
        path,
        lane=lane,
        start_source="training_opening_corpus" if corpus else "standard_initial_state",
        seed=seed,
    )
    write_json(workdir / f"{lane}_replay_manifest.json", manifest)
    return path, kept, manifest


def truncate_matched_whole_games(
    control_rows: list[dict[str, Any]],
    aligned_rows: list[dict[str, Any]],
    *,
    seed: int,
    batch_size: int = 512,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Keep matched whole games with identical train/validation/batch budgets."""

    def cumulative(rows: list[dict[str, Any]]) -> dict[int, int]:
        lengths = Counter(int(row["game_index"]) for row in rows)
        total = 0
        result = {0: 0}
        for game in sorted(lengths):
            total += lengths[game]
            result[total] = game + 1
        return result

    control_counts, aligned_counts = cumulative(control_rows), cumulative(aligned_rows)
    for matched_rows in reversed(sorted(set(control_counts) & set(aligned_counts))):
        if matched_rows <= 0:
            continue
        control = control_rows[
            : sum(
                1
                for row in control_rows
                if int(row["game_index"]) < control_counts[matched_rows]
            )
        ]
        aligned = aligned_rows[
            : sum(
                1
                for row in aligned_rows
                if int(row["game_index"]) < aligned_counts[matched_rows]
            )
        ]
        control_train, control_validation = game_split(control, seed)
        aligned_train, aligned_validation = game_split(aligned, seed)
        control_train_rows = sum(
            int(row["game_index"]) in set(control_train) for row in control
        )
        aligned_train_rows = sum(
            int(row["game_index"]) in set(aligned_train) for row in aligned
        )
        control_validation_rows = len(control) - control_train_rows
        aligned_validation_rows = len(aligned) - aligned_train_rows
        if (
            control_train_rows == aligned_train_rows
            and control_validation_rows == aligned_validation_rows
            and math.ceil(control_train_rows / batch_size)
            == math.ceil(aligned_train_rows / batch_size)
        ):
            return control, aligned
    raise RuntimeError("could not match game-level train/validation and batch budgets")


def distribution_audit(
    rows: list[dict[str, Any]], evaluation_suites: list[Path]
) -> dict[str, Any]:
    """Measure transparent state coverage only; no evaluation outcome is read."""
    eval_states = [
        row["state"] for path in evaluation_suites for row in read_jsonl(path)
    ]
    eval_hashes = {canonical_key(state) for state in eval_states}
    replay_states = [_decoded_state(row) for row in rows]
    replay_hashes = {canonical_key(state) for state in replay_states}
    vectors = np.asarray(
        [
            [
                *state["player_pits"],
                *state["opponent_pits"],
                state["player_store"],
                state["opponent_store"],
                state["current_player"],
            ]
            for state in replay_states
        ],
        dtype=float,
    )
    distances = []
    for state in eval_states:
        vector = np.asarray(
            [
                *state["player_pits"],
                *state["opponent_pits"],
                state["player_store"],
                state["opponent_store"],
                state["current_player"],
            ],
            dtype=float,
        )
        distances.append(
            float(np.abs(vectors - vector).sum(axis=1).min())
            if len(vectors)
            else float("inf")
        )
    return {
        "exact_state_overlap": len(replay_hashes & eval_hashes),
        "nearest_board_l1": {
            "median": float(np.median(distances)),
            "p90": float(np.percentile(distances, 90)),
        },
        "player_distribution": dict(
            sorted(Counter(str(row["player"]) for row in rows).items())
        ),
        "phase_distribution": dict(
            sorted(Counter(_phase(state) for state in replay_states).items())
        ),
    }


def preflight(
    control: dict[str, Any], aligned: dict[str, Any]
) -> tuple[bool, list[str]]:
    """Apply the prespecified transparent coverage gate."""
    reasons = []
    if control["exact_state_overlap"] or aligned["exact_state_overlap"]:
        reasons.append("evaluation_state_leakage")
    for key, required in (("median", 0.20), ("p90", 0.10)):
        baseline = control["nearest_board_l1"][key]
        improvement = (
            0.0 if baseline == 0 else 1 - aligned["nearest_board_l1"][key] / baseline
        )
        if improvement < required:
            reasons.append(
                f"nearest_distance_{key}_improvement_below_{int(required * 100)}pct"
            )
    for stratum in ("player_distribution", "phase_distribution"):
        for key, count in control[stratum].items():
            if int(aligned[stratum].get(key, 0)) < 0.75 * int(count):
                reasons.append(f"{stratum}_{key}_lost_over_25pct")
    return not reasons, reasons


def replay_probe(
    *, candidate: Path, current: Path, rows: list[dict[str, Any]], seed: int
) -> dict[str, Any]:
    """Evaluate a candidate on one immutable replay domain."""
    probe_rows = probe_rows_for(rows)
    candidate_outputs = evaluate_raw_outputs(artifact_path=candidate, rows=probe_rows)[
        "outputs"
    ]
    current_outputs = evaluate_raw_outputs(artifact_path=current, rows=probe_rows)[
        "outputs"
    ]
    return {
        "policy": evaluate_policy_probe_metrics(
            rows=probe_rows,
            candidate_outputs=candidate_outputs,
            current_outputs=current_outputs,
        ),
        "value": value_metrics(probe_rows, candidate_outputs),
        "value_change_vs_current": value_change_metrics(
            probe_rows, candidate_outputs, current_outputs
        ),
        "seed": seed,
    }


def canonical_search_probe(
    *,
    candidate: Path,
    current: Path,
    rows: list[dict[str, Any]],
    seed: int,
    workers: int,
) -> dict[str, Any]:
    """Measure selected-move changes under the frozen runtime profile."""
    budget_pairs = ("384:256", "768:768", "1200:1200", "1200:256")
    sample = probe_rows_for(rows[: min(len(rows), 256)])
    search_rows = build_search_probe_rows(sample, budget_pairs)
    schedule = parse_cpuct_schedule_json('{"768:768":0.90}')
    candidate_outputs = evaluate_search_outputs(
        artifact_path=candidate,
        rows=search_rows,
        default_c_puct=1.25,
        cpuct_schedule=schedule,
        tactical_root_bias=0.0,
        seed=seed,
        workers=workers,
    )
    current_outputs = evaluate_search_outputs(
        artifact_path=current,
        rows=search_rows,
        default_c_puct=1.25,
        cpuct_schedule=schedule,
        tactical_root_bias=0.0,
        seed=seed,
        workers=workers,
    )
    return evaluate_search_probe_metrics(
        rows=search_rows,
        candidate_outputs=candidate_outputs,
        current_outputs=current_outputs,
    )


def probe_rows_for(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Add the raw-state fields required by shared probe APIs to replay rows."""
    result = []
    for row in rows:
        state = _decoded_state(row)
        legal_moves = [int(move) for move in row.get("legal_moves", [])]
        result.append(
            {
                **row,
                "raw_state": state,
                "legal_mask": [int(move in legal_moves) for move in range(6)],
                "phase": _phase(state),
                "seat_context": f"player_{int(row['player'])}",
                "teacher_puct_policy": row["policy"],
                "budget_context": "selfplay_anchor",
            }
        )
    return result


def named_artifact_link(workdir: Path, name: str, target: Path) -> Path:
    """Expose a unique benchmark label without copying candidate weights."""
    link = workdir / name
    if link.exists() or link.is_symlink():
        link.unlink()
    os.symlink(target, link, target_is_directory=True)
    return link


def paired_strength_screen(
    *,
    workdir: Path,
    suite: Path,
    current: Path,
    control: Path,
    aligned: Path,
    seed: int,
    workers: int,
) -> dict[str, Any]:
    """Run the frozen medium-style paired screen and opening bootstrap CIs."""
    report = run_opening_suite_benchmark(
        workdir=str(workdir),
        suite=str(suite),
        current=str(current),
        candidates=",".join(str(path) for path in (current, control, aligned)),
        budget_pairs="384:256,768:256,768:768,1200:1200,1200:256,256:768",
        games_per_opening=2,
        seed=seed,
        workers=workers,
        timeout=14400,
        seed_contract=SEED_CONTRACT_VERSION,
        seed_ledger_output=str(workdir / "seed_ledger.jsonl"),
    )
    labels = {"current": current.name, "control": control.name, "aligned": aligned.name}
    candidate_reports = {
        name: find_candidate_report(report, label) for name, label in labels.items()
    }
    if any(value is None for value in candidate_reports.values()):
        raise RuntimeError("paired benchmark did not report every artifact")
    candidates = {
        name: benchmark_budget_results(value)
        for name, value in candidate_reports.items()
        if value is not None
    }
    suite_rows = {
        "screen": {
            "candidates": {
                name: {"budget_results": budgets}
                for name, budgets in candidates.items()
            }
        }
    }
    comparisons = {}
    for comparison, left, right in (
        ("aligned_minus_control", "aligned", "control"),
        ("aligned_minus_current", "aligned", "current"),
        ("control_minus_current", "control", "current"),
    ):
        comparisons[comparison] = {
            budget: bootstrap_ci(
                pooled_per_opening_differences(
                    suite_rows=suite_rows,
                    candidate_a=left,
                    candidate_b=right,
                    budget_pair=budget,
                    metric_key="ds",
                ),
                seed=seed,
            )
            for budget in candidates["aligned"]
        }
    return {
        "report_sha256": sha256_file(workdir / "temperature_benchmark_report.json"),
        "budgets": candidates,
        "paired_opening_bootstrap_95": comparisons,
    }


def medium_strength_pass(screen: dict[str, Any]) -> bool:
    """Apply the prespecified aligned-versus-control and current medium gate."""
    control = screen["paired_opening_bootstrap_95"]["aligned_minus_control"]
    current = screen["paired_opening_bootstrap_95"]["aligned_minus_current"]
    return bool(
        control["384:256"]["mean"] >= 0.03
        and control["384:256"]["lower"] > 0
        and control["768:768"]["mean"] >= -0.02
        and control["1200:1200"]["mean"] >= -0.02
        and control["1200:256"]["mean"] >= -0.02
        and current["384:256"]["mean"] > 0
        and all(
            current[key]["mean"] >= -0.03
            for key in ("768:768", "1200:1200", "1200:256")
        )
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workdir", default=str(DEFAULT_WORKDIR))
    parser.add_argument("--current", default="model-artifact/current")
    parser.add_argument("--medium-suite", required=True)
    parser.add_argument("--fixed-large-suite", required=True)
    parser.add_argument(
        "--heldout-suites", required=True, help="Comma-separated seeds 43-54 suites"
    )
    parser.add_argument(
        "--expected-current-weights-sha256", default=EXPECTED_CURRENT_SHA256
    )
    parser.add_argument("--rows-per-lane", type=int, default=40000)
    parser.add_argument("--selfplay-simulations", type=int, default=384)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--workers", type=int, default=24)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    workdir, current = Path(args.workdir), Path(args.current)
    workdir.mkdir(parents=True, exist_ok=True)
    weights = current / "weights.json"
    if sha256_file(weights) != args.expected_current_weights_sha256:
        raise RuntimeError("current weights hash mismatch")
    heldout = [Path(item) for item in args.heldout_suites.split(",") if item]
    suites = [Path(args.medium_suite), Path(args.fixed_large_suite), *heldout]
    runtime_profile = {
        "tactical_root_bias": 0.0,
        "default_c_puct": 1.25,
        "c_puct_schedule": {"768:768": 0.90},
    }
    try:
        corpus, corpus_manifest = build_training_opening_corpus(
            out_dir=workdir, exclusion_suites=suites, seed=args.seed
        )
    except CorpusPreflightError as exc:
        summary = {
            "schema": SCHEMA,
            "current_weights_sha256": sha256_file(weights),
            "runtime_profile": runtime_profile,
            "training_opening_corpus": exc.manifest,
            "classification": "distribution_alignment_preflight_failed",
            "stop_reasons": [exc.reason],
        }
        write_json(workdir / "summary_metrics.json", summary)
        write_json(
            REPO_ROOT
            / "docs/data/alphazero-lite-distribution-aligned-selfplay-summary.json",
            summary,
        )
        (
            REPO_ROOT / "docs/alphazero-lite-distribution-aligned-selfplay-results.md"
        ).write_text(
            "# AlphaZero-Lite Distribution-Aligned Self-Play Results\n\n```json\n"
            + json.dumps(summary, indent=2, sort_keys=True)
            + "\n```\n",
            encoding="utf-8",
        )
        print(
            json.dumps(
                {"classification": summary["classification"], "workdir": str(workdir)}
            )
        )
        return 0
    checkpoint = workdir / "current.npz"
    from ml.alphazero_lite.pipeline import materialize_weights_json_checkpoint

    materialize_weights_json_checkpoint(weights_path=weights, out_path=checkpoint)
    control_path, control_rows, control_manifest = generate_lane(
        lane="standard_start_control",
        workdir=workdir,
        checkpoint=checkpoint,
        corpus=None,
        target_rows=args.rows_per_lane,
        seed=args.seed,
        simulations=args.selfplay_simulations,
    )
    aligned_path, aligned_rows, aligned_manifest = generate_lane(
        lane="opening_seeded",
        workdir=workdir,
        checkpoint=checkpoint,
        corpus=corpus,
        target_rows=args.rows_per_lane,
        seed=args.seed,
        simulations=args.selfplay_simulations,
    )
    control_rows, aligned_rows = truncate_matched_whole_games(
        control_rows, aligned_rows, seed=args.seed
    )
    write_jsonl(control_path, control_rows)
    write_jsonl(aligned_path, aligned_rows)
    control_manifest = replay_manifest(
        control_rows,
        control_path,
        lane="standard_start_control",
        start_source="standard_initial_state",
        seed=args.seed,
    )
    aligned_manifest = replay_manifest(
        aligned_rows,
        aligned_path,
        lane="opening_seeded",
        start_source="training_opening_corpus",
        seed=args.seed,
    )
    write_json(
        workdir / "standard_start_control_replay_manifest.json", control_manifest
    )
    write_json(workdir / "opening_seeded_replay_manifest.json", aligned_manifest)
    control_audit, aligned_audit = (
        distribution_audit(control_rows, suites),
        distribution_audit(aligned_rows, suites),
    )
    passes, reasons = preflight(control_audit, aligned_audit)
    summary: dict[str, Any] = {
        "schema": SCHEMA,
        "current_weights_sha256": sha256_file(weights),
        "runtime_profile": runtime_profile,
        "training_opening_corpus": corpus_manifest,
        "replays": {
            "standard_start_control": control_manifest,
            "opening_seeded": aligned_manifest,
        },
        "distribution_audit": {
            "standard_start_control": control_audit,
            "opening_seeded": aligned_audit,
        },
        "stop_reasons": reasons,
    }
    if not passes:
        summary["classification"] = "distribution_alignment_preflight_failed"
    else:
        # Immutable manifests and duplicate runs are deliberately only reachable after leakage/coverage validation.
        runs = {}
        for name, path, rows in (
            ("standard_start_joint_heads_e1", control_path, control_rows),
            ("opening_seeded_joint_heads_e1", aligned_path, aligned_rows),
        ):
            lane_dir = workdir / name
            audit_path = lane_dir / "replay_audit.json"
            write_json(
                audit_path,
                replay_manifest(
                    rows, path, lane=name, start_source=name, seed=args.seed
                ),
            )
            build_manifest(
                rows=rows,
                workdir=lane_dir,
                current=current,
                replay=path,
                replay_audit=audit_path,
                seed=args.seed,
                epochs=1,
                batch_size=512,
            )
            manifest_path = lane_dir / "training_manifest.json"
            device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            run_prefix = "control" if name.startswith("standard") else "aligned"
            run_a, run_b = (
                train_fixed_manifest(manifest_path, device, f"{run_prefix}_run_a"),
                train_fixed_manifest(manifest_path, device, f"{run_prefix}_run_b"),
            )
            runs[name] = {
                "manifest": json.loads(manifest_path.read_text()),
                f"{run_prefix}_run_a": {
                    k: v for k, v in run_a.items() if not isinstance(v, np.ndarray)
                },
                f"{run_prefix}_run_b": {
                    k: v for k, v in run_b.items() if not isinstance(v, np.ndarray)
                },
                "reproducibility": compare_runs(run_a, run_b),
            }
        summary["training"] = runs
        if not all(run["reproducibility"]["passes"] for run in runs.values()):
            summary["classification"] = "full_scale_training_nondeterministic"
            summary["stop_reasons"].append("same_device_training_diverged")
        else:
            control_artifact = named_artifact_link(
                workdir,
                "standard_start_joint_heads_e1",
                Path(
                    runs["standard_start_joint_heads_e1"]["control_run_a"]["artifact"]
                ),
            )
            aligned_artifact = named_artifact_link(
                workdir,
                "opening_seeded_joint_heads_e1",
                Path(
                    runs["opening_seeded_joint_heads_e1"]["aligned_run_a"]["artifact"]
                ),
            )
            summary["cross_domain_replay_probes"] = {
                "standard_candidate_on_standard_validation": replay_probe(
                    candidate=control_artifact,
                    current=current,
                    rows=control_rows,
                    seed=args.seed,
                ),
                "standard_candidate_on_opening_seeded_validation": replay_probe(
                    candidate=control_artifact,
                    current=current,
                    rows=aligned_rows,
                    seed=args.seed,
                ),
                "aligned_candidate_on_opening_seeded_validation": replay_probe(
                    candidate=aligned_artifact,
                    current=current,
                    rows=aligned_rows,
                    seed=args.seed,
                ),
                "aligned_candidate_on_standard_validation": replay_probe(
                    candidate=aligned_artifact,
                    current=current,
                    rows=control_rows,
                    seed=args.seed,
                ),
            }
            summary["canonical_search_probes"] = {
                "standard": canonical_search_probe(
                    candidate=control_artifact,
                    current=current,
                    rows=control_rows,
                    seed=args.seed,
                    workers=args.workers,
                ),
                "aligned": canonical_search_probe(
                    candidate=aligned_artifact,
                    current=current,
                    rows=aligned_rows,
                    seed=args.seed,
                    workers=args.workers,
                ),
            }
            medium = paired_strength_screen(
                workdir=workdir / "medium",
                suite=Path(args.medium_suite),
                current=current,
                control=control_artifact,
                aligned=aligned_artifact,
                seed=args.seed,
                workers=args.workers,
            )
            summary["medium_strength"] = medium
            if not medium_strength_pass(medium):
                aligned_vs_control = medium["paired_opening_bootstrap_95"][
                    "aligned_minus_control"
                ]["384:256"]["mean"]
                summary["classification"] = (
                    "distribution_shift_not_primary_bottleneck"
                    if aligned_vs_control < 0.03
                    else "distribution_alignment_improves_learning_but_not_strength"
                )
                summary["stop_reasons"].append("medium_strength_gate_failed")
            else:
                fixed = paired_strength_screen(
                    workdir=workdir / "fixed_large",
                    suite=Path(args.fixed_large_suite),
                    current=current,
                    control=control_artifact,
                    aligned=aligned_artifact,
                    seed=args.seed,
                    workers=args.workers,
                )
                summary["fixed_large_strength"] = fixed
                fixed_current = fixed["paired_opening_bootstrap_95"][
                    "aligned_minus_current"
                ]
                fixed_pass = (
                    fixed_current["384:256"]["mean"] >= 0.05
                    and fixed_current["384:256"]["lower"] > 0.01
                    and fixed_current["768:768"]["mean"] >= -0.05
                    and fixed_current["1200:1200"]["mean"] >= -0.03
                    and fixed_current["1200:256"]["mean"] >= -0.03
                )
                if not fixed_pass:
                    summary["classification"] = (
                        "distribution_alignment_improves_learning_but_not_strength"
                    )
                    summary["stop_reasons"].append("fixed_large_qualification_failed")
                else:
                    summary["heldout_strength"] = {
                        path.name: paired_strength_screen(
                            workdir=workdir / f"heldout_{index}",
                            suite=path,
                            current=current,
                            control=control_artifact,
                            aligned=aligned_artifact,
                            seed=args.seed,
                            workers=args.workers,
                        )
                        for index, path in enumerate(heldout)
                    }
                    summary["classification"] = (
                        "distribution_aligned_joint_heads_candidate"
                    )
                    summary["stop_reasons"].append("promotion_not_run_by_protocol")
    write_json(workdir / "summary_metrics.json", summary)
    write_json(
        REPO_ROOT
        / "docs/data/alphazero-lite-distribution-aligned-selfplay-summary.json",
        summary,
    )
    (
        REPO_ROOT / "docs/alphazero-lite-distribution-aligned-selfplay-results.md"
    ).write_text(
        "# AlphaZero-Lite Distribution-Aligned Self-Play Results\n\n```json\n"
        + json.dumps(summary, indent=2, sort_keys=True)
        + "\n```\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {"classification": summary["classification"], "workdir": str(workdir)}
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
