#!/usr/bin/env python3
"""Opening-distribution-aligned PUCT replay ablation.

The only lane treatment is ``start_state_mode``.  In particular, replay is
generated by :func:`self_play.run_self_play_worker`, rather than by a second
implementation of PUCT or target construction.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import random
import sys
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Sequence

import numpy as np
import torch

REPO_ROOT = Path(__file__).resolve().parents[2]
if __package__ in (None, ""):
    sys.path.append(str(REPO_ROOT))

from ml.alphazero_lite.build_opening_suite import (  # noqa: E402
    canonical_key,
    deduplicate_openings,
    enumerate_legal_prefixes,
    select_diverse,
    stratify_openings,
)
from ml.alphazero_lite.run_deterministic_joint_heads_iteration import (  # noqa: E402
    build_manifest,
    compare_runs,
    game_split,
    train_fixed_manifest,
    value_change_metrics,
    value_metrics,
)
from ml.alphazero_lite.run_current_init_policy_only_distillation_preflight import (  # noqa: E402
    evaluate_policy_probe_metrics,
    evaluate_raw_outputs,
)
from ml.alphazero_lite.run_terminal_outcome_selfplay_iteration_smoke import (  # noqa: E402
    build_search_probe_rows,
    evaluate_search_outputs,
    evaluate_search_probe_metrics,
)
from ml.alphazero_lite.run_control_ep2_puct_head_preflight import (  # noqa: E402
    benchmark_budget_results,
    bootstrap_ci,
    find_candidate_report,
    pooled_per_opening_differences,
    run_opening_suite_benchmark,
)
from ml.alphazero_lite.cpuct_schedule import parse_cpuct_schedule_json  # noqa: E402
from ml.alphazero_lite.evaluation_seed_contract import SEED_CONTRACT_VERSION  # noqa: E402
from ml.alphazero_lite.self_play import (  # noqa: E402
    CheckpointEvaluator,
    PRESET_POOL_START_STATE_MODE,
    STANDARD_START_STATE_MODE,
    run_self_play_worker,
    standard_start_state,
)

EXPECTED_CURRENT_SHA256 = (
    "8d70e90a684caf946ab3f3e5d81a24e65be939b5be932930c389945fd9bb4e7a"
)
SCHEMA = "azlite_distribution_aligned_selfplay_v1"
CORPUS_SIZE = 2048
OPENING_PLIES = (2, 4, 6)
EXPECTED_CORPUS_SHA256 = (
    "8922c6cbda4e23184b81164c36880e5837b6a1693cb27168355d6f87b97d709a"
)
DEFAULT_WORKDIR = Path("/tmp/azlite_distribution_aligned_selfplay")


class CorpusPreflightError(RuntimeError):
    """A required corpus stratum cannot satisfy the frozen exclusions."""

    def __init__(self, manifest: dict[str, Any], reason: str):
        super().__init__(reason)
        self.manifest = manifest
        self.reason = reason


def sha256_file(path: Path) -> str:
    """Return a content digest."""
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(65536), b""):
            digest.update(block)
    return digest.hexdigest()


def write_json(path: Path, payload: dict[str, Any]) -> None:
    """Write stable, reviewable JSON."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    """Read JSONL records in their persisted order."""
    with path.open(encoding="utf-8") as handle:
        return [json.loads(line) for line in handle if line.strip()]


def write_jsonl(path: Path, rows: list[dict[str, Any]]) -> None:
    """Write compact JSONL records."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        for row in rows:
            handle.write(json.dumps(row, sort_keys=True) + "\n")


def suite_identities(
    paths: list[Path],
) -> tuple[set[str], set[tuple[int, ...]], dict[str, str]]:
    """Return exact state/prefix exclusions and input hashes for frozen suites."""
    states: set[str] = set()
    prefixes: set[tuple[int, ...]] = set()
    hashes: dict[str, str] = {}
    for path in paths:
        rows = read_jsonl(path)
        hashes[str(path)] = sha256_file(path)
        for row in rows:
            states.add(canonical_key(row["state"]))
            prefixes.add(tuple(int(move) for move in row.get("prefix_moves", [])))
            for alternate in row.get("alternate_prefixes", []):
                prefixes.add(tuple(int(move) for move in alternate))
    return states, prefixes, hashes


def opening_depth_feasibility(
    exclusion_suites: list[Path],
) -> tuple[dict[str, Any], set[int]]:
    """Audit every requested opening stratum before selecting training starts."""
    excluded_states, excluded_prefixes, exclusion_hashes = suite_identities(
        exclusion_suites
    )
    report: dict[str, Any] = {
        "schema": "azlite_opening_depth_feasibility_v1",
        "requested_depths": list(OPENING_PLIES),
        "exclusion_suite_hashes": exclusion_hashes,
        "depths": {},
    }
    feasible = set()
    for depth in OPENING_PLIES:
        raw = [
            entry for entry in enumerate_legal_prefixes(depth) if entry["ply"] == depth
        ]
        unique, _duplicates, duplicate_count = deduplicate_openings(raw)
        exact_prefixes = {
            tuple(entry["prefix_moves"])
            for path in exclusion_suites
            for entry in read_jsonl(path)
        }
        alternate_prefixes = {
            tuple(prefix)
            for path in exclusion_suites
            for entry in read_jsonl(path)
            for prefix in entry.get("alternate_prefixes", [])
        }
        excluded_by_state = sum(
            canonical_key(entry["state"]) in excluded_states for entry in unique
        )
        excluded_by_prefix = sum(
            tuple(entry["prefix_moves"]) in exact_prefixes for entry in unique
        )
        excluded_by_alternate = sum(
            tuple(entry["prefix_moves"]) in alternate_prefixes
            or any(
                tuple(prefix) in excluded_prefixes
                for prefix in entry.get("alternate_prefixes", [])
            )
            for entry in unique
        )
        eligible = [
            entry
            for entry in unique
            if canonical_key(entry["state"]) not in excluded_states
            and tuple(entry["prefix_moves"]) not in excluded_prefixes
            and not any(
                tuple(prefix) in excluded_prefixes
                for prefix in entry.get("alternate_prefixes", [])
            )
        ]
        if eligible:
            feasible.add(depth)
        report["depths"][str(depth)] = {
            "raw_legal_prefixes": len(raw),
            "unique_resulting_states": len(unique),
            "duplicate_transposed_prefixes": duplicate_count,
            "excluded_by_exact_evaluation_state": excluded_by_state,
            "excluded_by_canonical_prefix": excluded_by_prefix,
            "excluded_by_alternate_prefix": excluded_by_alternate,
            "eligible_after_all_exclusions": len(eligible),
        }
    report["required_feasible_depths"] = sorted(feasible)
    report["structurally_unavailable_depths"] = sorted(set(OPENING_PLIES) - feasible)
    report["ply2_unavailable_due_frozen_eval_exhaustion"] = (
        report["depths"]["2"]["eligible_after_all_exclusions"] == 0
    )
    return report, feasible


def build_training_opening_corpus(
    *,
    out_dir: Path,
    exclusion_suites: list[Path],
    seed: int,
    target_size: int = CORPUS_SIZE,
) -> tuple[Path, dict[str, Any]]:
    """Build a stratified, exact-disjoint corpus using evaluation's prefix generator."""
    excluded_states, excluded_prefixes, exclusion_hashes = suite_identities(
        exclusion_suites
    )
    feasibility, required_feasible_depths = opening_depth_feasibility(exclusion_suites)
    write_json(out_dir / "opening_depth_feasibility.json", feasibility)
    if (
        target_size == CORPUS_SIZE
        and feasibility["depths"]["2"]["eligible_after_all_exclusions"] != 0
    ):
        raise CorpusPreflightError(
            feasibility, "ply-2 eligibility contradicts frozen PR #175 exhaustion"
        )
    prefixes = [
        entry
        for depth in OPENING_PLIES
        for entry in enumerate_legal_prefixes(depth)
        if entry["ply"] == depth
    ]
    unique, _duplicates, duplicate_count = deduplicate_openings(prefixes)
    eligible = [
        entry
        for entry in stratify_openings(unique)
        if canonical_key(entry["state"]) not in excluded_states
        and tuple(entry["prefix_moves"]) not in excluded_prefixes
        and not any(
            tuple(prefix) in excluded_prefixes
            for prefix in entry.get("alternate_prefixes", [])
        )
    ]
    if len(eligible) < target_size:
        raise RuntimeError(
            f"only {len(eligible)} disjoint starts available; need {target_size}"
        )
    selected = select_diverse(eligible, target_size, seed)
    # ``select_diverse`` intentionally stops when a bucket quota is exhausted.
    # Fill any residual budget from the same eligible population, retaining its
    # deterministic RNG and never weakening the exclusion contract.
    selected_hashes = {canonical_key(entry["state"]) for entry in selected}
    remainder = [
        entry
        for entry in eligible
        if canonical_key(entry["state"]) not in selected_hashes
    ]
    rng = random.Random(seed)
    rng.shuffle(remainder)
    selected.extend(remainder[: max(0, target_size - len(selected))])
    records = [
        {
            "state": entry["state"],
            "metadata": {
                "prefix_moves": entry["prefix_moves"],
                "opening_ply": entry["ply"],
                "phase": entry["phase_bucket"],
                "side_to_move": entry["side_to_move"],
            },
        }
        for entry in selected
    ]
    corpus_path = out_dir / "training_opening_corpus.jsonl"
    write_jsonl(corpus_path, records)
    hashes = [canonical_key(record["state"]) for record in records]
    manifest = {
        "schema": "training_opening_corpus_v1",
        "generator_version": "build_opening_suite_v1",
        "generator_seed": seed,
        "state_count": len(records),
        "prefix_depth_distribution": dict(
            sorted(
                Counter(record["metadata"]["opening_ply"] for record in records).items()
            )
        ),
        "player_to_move_distribution": dict(
            sorted(
                Counter(record["state"]["current_player"] for record in records).items()
            )
        ),
        "phase_distribution": dict(
            sorted(Counter(record["metadata"]["phase"] for record in records).items())
        ),
        "exact_state_hashes": hashes,
        "corpus_sha256": sha256_file(corpus_path),
        "exclusion_suite_hashes": exclusion_hashes,
        "exact_overlap_counts": {
            "states": len(set(hashes) & excluded_states),
            "prefixes": sum(
                tuple(r["metadata"]["prefix_moves"]) in excluded_prefixes
                for r in records
            ),
            "alternate_prefixes": sum(
                any(
                    tuple(prefix) in excluded_prefixes
                    for prefix in entry.get("alternate_prefixes", [])
                )
                for entry in selected
            ),
        },
        "duplicate_counts": {
            "enumeration": duplicate_count,
            "corpus_states": len(hashes) - len(set(hashes)),
        },
        "required_feasible_depths": sorted(required_feasible_depths),
        "structurally_unavailable_depths": sorted(
            set(OPENING_PLIES) - required_feasible_depths
        ),
        "ply2_unavailable_due_frozen_eval_exhaustion": feasibility[
            "ply2_unavailable_due_frozen_eval_exhaustion"
        ],
    }
    if (
        len(hashes) != target_size
        or len(set(hashes)) != target_size
        or any(manifest["exact_overlap_counts"].values())
    ):
        raise RuntimeError(
            "training opening corpus failed uniqueness or exclusion audit: "
            f"rows={len(hashes)} unique={len(set(hashes))} "
            f"overlap={manifest['exact_overlap_counts']}"
        )
    if (
        target_size == CORPUS_SIZE
        and manifest["corpus_sha256"] != EXPECTED_CORPUS_SHA256
    ):
        raise RuntimeError(
            "frozen training opening corpus hash changed; refusing a new start distribution"
        )
    write_json(out_dir / "training_opening_corpus_manifest.json", manifest)
    missing_depths = sorted(
        required_feasible_depths - set(manifest["prefix_depth_distribution"])
    )
    if missing_depths or len(manifest["player_to_move_distribution"]) != 2:
        details = []
        if missing_depths:
            details.append(f"missing required opening depths: {missing_depths}")
        if len(manifest["player_to_move_distribution"]) != 2:
            details.append("both players are not represented")
        raise CorpusPreflightError(manifest, "; ".join(details))
    return corpus_path, manifest


def _decoded_state(row: dict[str, Any]) -> dict[str, Any]:
    values = row["state"]
    return {
        "player_pits": [round(v * 48) for v in values[:6]],
        "opponent_pits": [round(v * 48) for v in values[6:12]],
        "player_store": round(values[12] * 48),
        "opponent_store": round(values[13] * 48),
        "current_player": round(values[14]),
    }


def _phase(state: dict[str, Any]) -> str:
    stones = sum(state["player_pits"]) + sum(state["opponent_pits"])
    return "opening" if stones > 24 else "midgame" if stones > 12 else "late"


def replay_manifest(
    rows: list[dict[str, Any]], path: Path, *, lane: str, start_source: str, seed: int
) -> dict[str, Any]:
    """Summarize persisted replay without altering target semantics."""
    states = [_decoded_state(row) for row in rows]
    policies = [row["policy"] for row in rows]
    entropies = [
        -sum(p * math.log(p, 2) for p in policy if p > 0) for policy in policies
    ]
    return {
        "lane": lane,
        "replay_sha256": sha256_file(path),
        "row_count": len(rows),
        "game_count": len({int(row["game_index"]) for row in rows}),
        "unique_state_count": len({canonical_key(state) for state in states}),
        "start_state_source": start_source,
        "start_state_hashes": sorted(
            {
                str(row.get("start_state_hash", canonical_key(standard_start_state())))
                for row in rows
            }
        ),
        "player_distribution": dict(
            sorted(Counter(str(row["player"]) for row in rows).items())
        ),
        "phase_distribution": dict(
            sorted(Counter(_phase(state) for state in states).items())
        ),
        "policy_entropy": {"mean": float(np.mean(entropies)) if entropies else 0.0},
        "terminal_target_distribution": dict(
            sorted(Counter(str(row["value"]) for row in rows).items())
        ),
        "random_seeds": {"base_seed": seed},
    }


def generate_lane(
    *,
    lane: str,
    workdir: Path,
    checkpoint: Path,
    corpus: Path | None,
    target_rows: int,
    seed: int,
    simulations: int,
    output_stem: str = "replay",
) -> tuple[Path, list[dict[str, Any]], dict[str, Any]]:
    """Generate whole games until the requested row budget is reached."""
    rows: list[dict[str, Any]] = []
    game_index = 0
    while len(rows) < target_rows:
        shard = workdir / f"{lane}_{game_index}.jsonl"
        result = run_self_play_worker(
            worker_id=0,
            start_index=game_index,
            games=32,
            seed=seed,
            seed_pool=[seed],
            checkpoint=str(checkpoint),
            input_encoding="kalah_v3",
            simulations=simulations,
            c_puct=1.25,
            temperature_threshold=8,
            temperature=0.67,
            temperature_late=0.0,
            dirichlet_alpha=0.3,
            dirichlet_epsilon=0.25,
            max_moves=200,
            shard_path=str(shard),
            root_policy_mode="visit_count",
            write_game_metadata=True,
            write_root_target_telemetry=True,
            start_state_mode=PRESET_POOL_START_STATE_MODE
            if corpus
            else STANDARD_START_STATE_MODE,
            start_state_pool_path=None if corpus is None else str(corpus),
        )
        del result
        rows.extend(read_jsonl(shard))
        game_index += 32
    # The requested budget is a lower bound: preserve the final complete game
    # rather than dropping it to land below the row target.
    kept = rows
    lane_name = "standard" if lane == "standard_start_control" else "opening_seeded"
    path = workdir / (
        f"{output_stem}_{lane_name}_replay.jsonl"
        if output_stem == "pilot"
        else f"{output_stem}_{lane_name}.jsonl"
    )
    write_jsonl(path, kept)
    manifest = replay_manifest(
        kept,
        path,
        lane=lane,
        start_source="training_opening_corpus" if corpus else "standard_initial_state",
        seed=seed,
    )
    write_json(workdir / f"{lane}_replay_manifest.json", manifest)
    return path, kept, manifest


def truncate_matched_whole_games(
    control_rows: list[dict[str, Any]],
    aligned_rows: list[dict[str, Any]],
    *,
    seed: int,
    batch_size: int = 512,
    allow_nearest: bool = False,
    minimum_rows: int = 0,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    """Keep matched whole games with identical train/validation/batch budgets."""

    def cumulative(rows: list[dict[str, Any]]) -> dict[int, int]:
        lengths = Counter(int(row["game_index"]) for row in rows)
        total = 0
        result = {0: 0}
        for game in sorted(lengths):
            total += lengths[game]
            result[total] = game + 1
        return result

    control_counts, aligned_counts = cumulative(control_rows), cumulative(aligned_rows)
    for matched_rows in reversed(sorted(set(control_counts) & set(aligned_counts))):
        if matched_rows <= 0:
            continue
        control = control_rows[
            : sum(
                1
                for row in control_rows
                if int(row["game_index"]) < control_counts[matched_rows]
            )
        ]
        aligned = aligned_rows[
            : sum(
                1
                for row in aligned_rows
                if int(row["game_index"]) < aligned_counts[matched_rows]
            )
        ]
        control_train, control_validation = game_split(control, seed)
        aligned_train, aligned_validation = game_split(aligned, seed)
        control_train_rows = sum(
            int(row["game_index"]) in set(control_train) for row in control
        )
        aligned_train_rows = sum(
            int(row["game_index"]) in set(aligned_train) for row in aligned
        )
        control_validation_rows = len(control) - control_train_rows
        aligned_validation_rows = len(aligned) - aligned_train_rows
        if (
            control_train_rows == aligned_train_rows
            and control_validation_rows == aligned_validation_rows
            and math.ceil(control_train_rows / batch_size)
            == math.ceil(aligned_train_rows / batch_size)
        ):
            return control, aligned
    if not allow_nearest:
        raise RuntimeError(
            "could not match game-level train/validation and batch budgets"
        )

    # Pilot games cannot be split; use the closest complete-game pair when exact
    # train/validation equality is unavailable at the small fixed row budget.
    candidates = []
    for control_total, control_end in control_counts.items():
        for aligned_total, aligned_end in aligned_counts.items():
            if not control_total or not aligned_total:
                continue
            control = [
                row for row in control_rows if int(row["game_index"]) < control_end
            ]
            aligned = [
                row for row in aligned_rows if int(row["game_index"]) < aligned_end
            ]
            if min(len(control), len(aligned)) < minimum_rows:
                continue
            control_train, _ = game_split(control, seed)
            aligned_train, _ = game_split(aligned, seed)
            control_train_rows = sum(
                int(row["game_index"]) in set(control_train) for row in control
            )
            aligned_train_rows = sum(
                int(row["game_index"]) in set(aligned_train) for row in aligned
            )
            candidates.append(
                (
                    (
                        abs(len(control) - len(aligned)),
                        -min(len(control), len(aligned)),
                        int(
                            math.ceil(control_train_rows / batch_size)
                            != math.ceil(aligned_train_rows / batch_size)
                        ),
                        abs(control_train_rows - aligned_train_rows),
                    ),
                    control,
                    aligned,
                )
            )
    if candidates:
        _score, control, aligned = min(candidates, key=lambda item: item[0])
        return control, aligned
    raise RuntimeError("could not retain any complete pilot games")


def distribution_audit(
    rows: list[dict[str, Any]],
    evaluation_suites: list[Path],
    checkpoint: Path | None = None,
) -> dict[str, Any]:
    """Measure coverage and distinguish direct seeding from later trajectory overlap."""
    eval_rows = [(path, row) for path in evaluation_suites for row in read_jsonl(path)]
    eval_states = [row["state"] for _path, row in eval_rows]
    eval_hashes = {canonical_key(state) for state in eval_states}
    replay_states = [_decoded_state(row) for row in rows]
    replay_hashes = {canonical_key(state) for state in replay_states}
    eval_prefixes = {
        tuple(int(move) for move in row.get("prefix_moves", []))
        for _path, row in eval_rows
    }
    start_rows = {int(row["game_index"]): row for row in rows if "game_index" in row}
    seeded_starts = {
        str(row.get("start_state_hash"))
        for row in start_rows.values()
        if row.get("start_state_hash")
    }
    seeded_prefixes = {
        tuple(row.get("start_state_metadata", {}).get("prefix_moves", []))
        for row in start_rows.values()
        if row.get("start_state_metadata", {}).get("prefix_moves") is not None
    }
    vectors = np.asarray(
        [
            [
                *state["player_pits"],
                *state["opponent_pits"],
                state["player_store"],
                state["opponent_store"],
                state["current_player"],
            ]
            for state in replay_states
        ],
        dtype=float,
    )
    distances = []
    for state in eval_states:
        vector = np.asarray(
            [
                *state["player_pits"],
                *state["opponent_pits"],
                state["player_store"],
                state["opponent_store"],
                state["current_player"],
            ],
            dtype=float,
        )
        distances.append(
            float(np.abs(vectors - vector).sum(axis=1).min())
            if len(vectors)
            else float("inf")
        )
    overlap_rows = [
        state for state in replay_states if canonical_key(state) in eval_hashes
    ]
    overlap_by_depth: Counter[str] = Counter()
    overlap_by_phase: Counter[str] = Counter()
    eval_depth_by_hash: dict[str, set[str]] = defaultdict(set)
    for _path, row in eval_rows:
        eval_depth_by_hash[canonical_key(row["state"])].add(
            str(row.get("ply", "unknown"))
        )
    for state in overlap_rows:
        overlap_by_phase[_phase(state)] += 1
        for depth in eval_depth_by_hash[canonical_key(state)]:
            overlap_by_depth[depth] += 1
    legal_counts = [len(row.get("legal_moves", [])) for row in rows]
    store_differences = [
        state["player_store"] - state["opponent_store"] for state in replay_states
    ]
    visit_entropies = [
        -sum(
            (count / sum(row["root_visit_counts"]))
            * math.log(count / sum(row["root_visit_counts"]), 2)
            for count in row.get("root_visit_counts", [])
            if count > 0 and sum(row["root_visit_counts"]) > 0
        )
        for row in rows
        if row.get("root_visit_counts")
    ]
    current_values: list[float] = []
    if checkpoint is not None and rows:
        from ml.alphazero_lite.kalah_rules import KalahGame

        evaluator = CheckpointEvaluator(checkpoint, input_encoding="kalah_v3")
        current_values = [
            float(evaluator.evaluate(KalahGame.from_state(state))[1])
            for state in replay_states
        ]

    def summary(values: Sequence[float | int]) -> dict[str, float]:
        return {
            "mean": float(np.mean(values)) if values else 0.0,
            "p50": float(np.median(values)) if values else 0.0,
        }

    per_suite = {}
    family_distances: dict[str, list[float]] = defaultdict(list)
    for path in evaluation_suites:
        suite_states = [row["state"] for row in read_jsonl(path)]
        suite_distances = []
        for state in suite_states:
            vector = np.asarray(
                [
                    *state["player_pits"],
                    *state["opponent_pits"],
                    state["player_store"],
                    state["opponent_store"],
                    state["current_player"],
                ],
                dtype=float,
            )
            suite_distances.append(
                float(np.abs(vectors - vector).sum(axis=1).min())
                if len(vectors)
                else float("inf")
            )
        per_suite[path.stem] = {
            "median": float(np.median(suite_distances)),
            "p90": float(np.percentile(suite_distances, 90)),
        }
        if path.stem == "medium_eval":
            family = "medium"
        elif path.stem == "large_eval":
            family = "fixed_large"
        elif "heldout_seed" not in path.stem:
            family = "other"
        else:
            seed = int(path.stem.split("seed")[1].split("_")[0])
            family = "heldout_43_48" if seed <= 48 else "heldout_49_54"
        family_distances[family].extend(suite_distances)
        family_distances["pooled_evaluation_corpus"].extend(suite_distances)
    return {
        "seeded_start_state_overlap": len(seeded_starts & eval_hashes),
        "seeded_prefix_overlap": len(seeded_prefixes & eval_prefixes),
        "replay_trajectory_state_overlap": {
            "unique_overlapping_replay_states": len(replay_hashes & eval_hashes),
            "overlapping_replay_rows": len(overlap_rows),
            "fraction_unique_replay_states": len(replay_hashes & eval_hashes)
            / len(replay_hashes)
            if replay_hashes
            else 0.0,
            "fraction_replay_rows": len(overlap_rows) / len(rows) if rows else 0.0,
            "by_evaluation_opening_depth": dict(sorted(overlap_by_depth.items())),
            "by_phase": dict(sorted(overlap_by_phase.items())),
        },
        "nearest_board_l1": {
            "median": float(np.median(distances)),
            "p90": float(np.percentile(distances, 90)),
            "by_suite": per_suite,
            "by_evaluation_family": {
                family: {
                    "median": float(np.median(values)),
                    "p90": float(np.percentile(values, 90)),
                }
                for family, values in sorted(family_distances.items())
            },
        },
        "player_distribution": dict(
            sorted(Counter(str(row["player"]) for row in rows).items())
        ),
        "phase_distribution": dict(
            sorted(Counter(_phase(state) for state in replay_states).items())
        ),
        "legal_move_count_distribution": dict(
            sorted(Counter(map(str, legal_counts)).items())
        ),
        "store_difference_distribution": dict(
            sorted(Counter(map(str, store_differences)).items())
        ),
        "current_model_value_distribution": summary(current_values),
        "policy_entropy": summary(
            [
                -sum(p * math.log(p, 2) for p in row.get("policy", []) if p > 0)
                for row in rows
            ]
        ),
        "puct_visit_entropy": summary(visit_entropies),
    }


def preflight(
    control: dict[str, Any], aligned: dict[str, Any]
) -> tuple[bool, list[str]]:
    """Apply the prespecified transparent coverage gate."""
    reasons = []
    if control["seeded_start_state_overlap"] or aligned["seeded_start_state_overlap"]:
        reasons.append("seeded_start_state_leakage")
    if control["seeded_prefix_overlap"] or aligned["seeded_prefix_overlap"]:
        reasons.append("seeded_prefix_leakage")
    for key, required in (("median", 0.20), ("p90", 0.10)):
        baseline = control["nearest_board_l1"][key]
        improvement = (
            0.0 if baseline == 0 else 1 - aligned["nearest_board_l1"][key] / baseline
        )
        if improvement < required:
            reasons.append(
                f"nearest_distance_{key}_improvement_below_{int(required * 100)}pct"
            )
    for stratum in ("player_distribution", "phase_distribution"):
        for key, count in control[stratum].items():
            if int(aligned[stratum].get(key, 0)) < 0.75 * int(count):
                reasons.append(f"{stratum}_{key}_lost_over_25pct")
    return not reasons, reasons


def replay_probe(
    *, candidate: Path, current: Path, rows: list[dict[str, Any]], seed: int
) -> dict[str, Any]:
    """Evaluate a candidate on one immutable replay domain."""
    probe_rows = probe_rows_for(rows)
    candidate_outputs = evaluate_raw_outputs(artifact_path=candidate, rows=probe_rows)[
        "outputs"
    ]
    current_outputs = evaluate_raw_outputs(artifact_path=current, rows=probe_rows)[
        "outputs"
    ]
    return {
        "policy": evaluate_policy_probe_metrics(
            rows=probe_rows,
            candidate_outputs=candidate_outputs,
            current_outputs=current_outputs,
        ),
        "value": value_metrics(probe_rows, candidate_outputs),
        "value_change_vs_current": value_change_metrics(
            probe_rows, candidate_outputs, current_outputs
        ),
        "seed": seed,
    }


def canonical_search_probe(
    *,
    candidate: Path,
    current: Path,
    rows: list[dict[str, Any]],
    seed: int,
    workers: int,
) -> dict[str, Any]:
    """Measure selected-move changes under the frozen runtime profile."""
    budget_pairs = ("384:256", "768:768", "1200:1200", "1200:256")
    sample = probe_rows_for(rows[: min(len(rows), 256)])
    search_rows = build_search_probe_rows(sample, budget_pairs)
    schedule = parse_cpuct_schedule_json('{"768:768":0.90}')
    candidate_outputs = evaluate_search_outputs(
        artifact_path=candidate,
        rows=search_rows,
        default_c_puct=1.25,
        cpuct_schedule=schedule,
        tactical_root_bias=0.0,
        seed=seed,
        workers=workers,
    )
    current_outputs = evaluate_search_outputs(
        artifact_path=current,
        rows=search_rows,
        default_c_puct=1.25,
        cpuct_schedule=schedule,
        tactical_root_bias=0.0,
        seed=seed,
        workers=workers,
    )
    return evaluate_search_probe_metrics(
        rows=search_rows,
        candidate_outputs=candidate_outputs,
        current_outputs=current_outputs,
    )


def probe_rows_for(rows: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Add the raw-state fields required by shared probe APIs to replay rows."""
    result = []
    for row in rows:
        state = _decoded_state(row)
        legal_moves = [int(move) for move in row.get("legal_moves", [])]
        result.append(
            {
                **row,
                "raw_state": state,
                "legal_mask": [int(move in legal_moves) for move in range(6)],
                "phase": _phase(state),
                "seat_context": f"player_{int(row['player'])}",
                "teacher_puct_policy": row["policy"],
                "budget_context": "selfplay_anchor",
            }
        )
    return result


def named_artifact_link(workdir: Path, name: str, target: Path) -> Path:
    """Expose a unique benchmark label without copying candidate weights."""
    link = workdir / name
    if link.exists() or link.is_symlink():
        link.unlink()
    os.symlink(target, link, target_is_directory=True)
    return link


def paired_strength_screen(
    *,
    workdir: Path,
    suite: Path,
    current: Path,
    control: Path,
    aligned: Path,
    seed: int,
    workers: int,
) -> dict[str, Any]:
    """Run the frozen medium-style paired screen and opening bootstrap CIs."""
    report = run_opening_suite_benchmark(
        workdir=str(workdir),
        suite=str(suite),
        current=str(current),
        candidates=",".join(str(path) for path in (current, control, aligned)),
        budget_pairs="384:256,768:256,768:768,1200:1200,1200:256,256:768",
        games_per_opening=2,
        seed=seed,
        workers=workers,
        timeout=14400,
        seed_contract=SEED_CONTRACT_VERSION,
        seed_ledger_output=str(workdir / "seed_ledger.jsonl"),
    )
    labels = {"current": current.name, "control": control.name, "aligned": aligned.name}
    candidate_reports = {
        name: find_candidate_report(report, label) for name, label in labels.items()
    }
    if any(value is None for value in candidate_reports.values()):
        raise RuntimeError("paired benchmark did not report every artifact")
    candidates = {
        name: benchmark_budget_results(value)
        for name, value in candidate_reports.items()
        if value is not None
    }
    suite_rows = {
        "screen": {
            "candidates": {
                name: {"budget_results": budgets}
                for name, budgets in candidates.items()
            }
        }
    }
    comparisons = {}
    for comparison, left, right in (
        ("aligned_minus_control", "aligned", "control"),
        ("aligned_minus_current", "aligned", "current"),
        ("control_minus_current", "control", "current"),
    ):
        comparisons[comparison] = {
            budget: bootstrap_ci(
                pooled_per_opening_differences(
                    suite_rows=suite_rows,
                    candidate_a=left,
                    candidate_b=right,
                    budget_pair=budget,
                    metric_key="ds",
                ),
                seed=seed,
            )
            for budget in candidates["aligned"]
        }
    return {
        "report_sha256": sha256_file(workdir / "temperature_benchmark_report.json"),
        "budgets": candidates,
        "paired_opening_bootstrap_95": comparisons,
    }


def medium_strength_pass(screen: dict[str, Any]) -> bool:
    """Apply the prespecified aligned-versus-control and current medium gate."""
    control = screen["paired_opening_bootstrap_95"]["aligned_minus_control"]
    current = screen["paired_opening_bootstrap_95"]["aligned_minus_current"]
    return bool(
        control["384:256"]["mean"] >= 0.03
        and control["384:256"]["lower"] > 0
        and control["768:768"]["mean"] >= -0.02
        and control["1200:1200"]["mean"] >= -0.02
        and control["1200:256"]["mean"] >= -0.02
        and current["384:256"]["mean"] > 0
        and all(
            current[key]["mean"] >= -0.03
            for key in ("768:768", "1200:1200", "1200:256")
        )
    )


def heldout_qualification_pass(
    heldout: dict[str, dict[str, Any]],
) -> tuple[bool, dict[str, Any]]:
    """Aggregate held-out aligned-versus-current evidence before candidate labeling."""
    required_budgets = ("384:256", "768:768", "1200:1200", "1200:256")
    if not heldout:
        return False, {"reason": "no_heldout_results"}
    aggregate = {}
    for budget in required_budgets:
        samples = [
            screen["paired_opening_bootstrap_95"]["aligned_minus_current"][budget]
            for screen in heldout.values()
        ]
        aggregate[budget] = {
            "mean": float(np.mean([sample["mean"] for sample in samples])),
            "lower": float(min(sample["lower"] for sample in samples)),
            "suite_count": len(samples),
        }
    passes = bool(
        aggregate["384:256"]["mean"] >= 0.05
        and aggregate["384:256"]["lower"] > 0.01
        and aggregate["768:768"]["mean"] >= -0.05
        and aggregate["1200:1200"]["mean"] >= -0.03
        and aggregate["1200:256"]["mean"] >= -0.03
    )
    return passes, {"budgets": aggregate, "passes": passes}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workdir", default=str(DEFAULT_WORKDIR))
    parser.add_argument("--current", default="model-artifact/current")
    parser.add_argument("--medium-suite", required=True)
    parser.add_argument("--fixed-large-suite", required=True)
    parser.add_argument(
        "--heldout-suites", required=True, help="Comma-separated seeds 43-54 suites"
    )
    parser.add_argument(
        "--expected-current-weights-sha256", default=EXPECTED_CURRENT_SHA256
    )
    parser.add_argument("--rows-per-lane", type=int, default=40000)
    parser.add_argument("--pilot-rows-per-lane", type=int, default=5000)
    parser.add_argument("--selfplay-simulations", type=int, default=384)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--workers", type=int, default=24)
    return parser.parse_args()


def compact_summary(summary: dict[str, Any]) -> dict[str, Any]:
    """Remove per-state workdir detail from the committed report payload."""
    compact = json.loads(json.dumps(summary))
    corpus = compact.get("training_opening_corpus", {})
    corpus.pop("exact_state_hashes", None)
    return compact


def write_reports(summary: dict[str, Any]) -> None:
    """Write compact committed reports; full manifests remain in the workdir."""
    compact = compact_summary(summary)
    write_json(
        REPO_ROOT
        / "docs/data/alphazero-lite-distribution-aligned-selfplay-summary.json",
        compact,
    )
    feasibility = compact.get("opening_depth_feasibility", {}).get("depths", {})
    table = [
        "| Ply | Raw prefixes | Unique states | Duplicate prefixes | Excluded state | Excluded canonical | Excluded alternate | Eligible |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for depth in map(str, OPENING_PLIES):
        row = feasibility.get(depth, {})
        table.append(
            "| {depth} | {raw_legal_prefixes} | {unique_resulting_states} | {duplicate_transposed_prefixes} | {excluded_by_exact_evaluation_state} | {excluded_by_canonical_prefix} | {excluded_by_alternate_prefix} | {eligible_after_all_exclusions} |".format(
                depth=depth,
                **{
                    key: row.get(key, 0)
                    for key in (
                        "raw_legal_prefixes",
                        "unique_resulting_states",
                        "duplicate_transposed_prefixes",
                        "excluded_by_exact_evaluation_state",
                        "excluded_by_canonical_prefix",
                        "excluded_by_alternate_prefix",
                        "eligible_after_all_exclusions",
                    )
                },
            )
        )
    markdown = [
        "# AlphaZero-Lite Distribution-Aligned Self-Play Results",
        "",
        f"- Classification: `{compact.get('classification', 'incomplete')}`",
        f"- Stop reasons: `{'; '.join(compact.get('stop_reasons', [])) or 'none'}`",
        f"- Frozen corpus SHA256: `{compact.get('training_opening_corpus', {}).get('corpus_sha256', 'not built')}`",
        "- `ply2_unavailable_due_frozen_eval_exhaustion`: `true`",
        "",
        "## Structural Depth Availability",
        "",
        *table,
        "",
        "## Compact Record",
        "",
        "```json",
        json.dumps(compact, indent=2, sort_keys=True),
        "```",
        "",
    ]
    (
        REPO_ROOT / "docs/alphazero-lite-distribution-aligned-selfplay-results.md"
    ).write_text("\n".join(markdown), encoding="utf-8")


def main() -> int:
    args = parse_args()
    workdir, current = Path(args.workdir), Path(args.current)
    workdir.mkdir(parents=True, exist_ok=True)
    weights = current / "weights.json"
    if sha256_file(weights) != args.expected_current_weights_sha256:
        raise RuntimeError("current weights hash mismatch")
    heldout = [Path(item) for item in args.heldout_suites.split(",") if item]
    suites = [Path(args.medium_suite), Path(args.fixed_large_suite), *heldout]
    runtime_profile = {
        "tactical_root_bias": 0.0,
        "default_c_puct": 1.25,
        "c_puct_schedule": {"768:768": 0.90},
    }
    try:
        corpus, corpus_manifest = build_training_opening_corpus(
            out_dir=workdir, exclusion_suites=suites, seed=args.seed
        )
    except CorpusPreflightError as exc:
        summary = {
            "schema": SCHEMA,
            "current_weights_sha256": sha256_file(weights),
            "runtime_profile": runtime_profile,
            "training_opening_corpus": exc.manifest,
            "classification": "distribution_alignment_preflight_failed",
            "stop_reasons": [exc.reason],
        }
        write_json(workdir / "summary_metrics.json", summary)
        write_reports(summary)
        print(
            json.dumps(
                {"classification": summary["classification"], "workdir": str(workdir)}
            )
        )
        return 0
    checkpoint = workdir / "current.npz"
    from ml.alphazero_lite.pipeline import materialize_weights_json_checkpoint

    materialize_weights_json_checkpoint(weights_path=weights, out_path=checkpoint)
    feasibility = json.loads((workdir / "opening_depth_feasibility.json").read_text())
    pilot_control_path, pilot_control_rows, pilot_control_manifest = generate_lane(
        lane="standard_start_control",
        workdir=workdir,
        checkpoint=checkpoint,
        corpus=None,
        target_rows=args.pilot_rows_per_lane,
        seed=args.seed,
        simulations=args.selfplay_simulations,
        output_stem="pilot",
    )
    pilot_aligned_path, pilot_aligned_rows, pilot_aligned_manifest = generate_lane(
        lane="opening_seeded",
        workdir=workdir,
        checkpoint=checkpoint,
        corpus=corpus,
        target_rows=args.pilot_rows_per_lane,
        seed=args.seed,
        simulations=args.selfplay_simulations,
        output_stem="pilot",
    )
    pilot_control_rows, pilot_aligned_rows = truncate_matched_whole_games(
        pilot_control_rows,
        pilot_aligned_rows,
        seed=args.seed,
        allow_nearest=True,
        minimum_rows=args.pilot_rows_per_lane,
    )
    write_jsonl(pilot_control_path, pilot_control_rows)
    write_jsonl(pilot_aligned_path, pilot_aligned_rows)
    pilot_control_manifest = replay_manifest(
        pilot_control_rows,
        pilot_control_path,
        lane="standard_start_control",
        start_source="standard_initial_state",
        seed=args.seed,
    )
    pilot_aligned_manifest = replay_manifest(
        pilot_aligned_rows,
        pilot_aligned_path,
        lane="opening_seeded",
        start_source="training_opening_corpus",
        seed=args.seed,
    )
    write_json(workdir / "pilot_standard_replay_manifest.json", pilot_control_manifest)
    write_json(
        workdir / "pilot_opening_seeded_replay_manifest.json", pilot_aligned_manifest
    )
    control_audit, aligned_audit = (
        distribution_audit(pilot_control_rows, suites, checkpoint),
        distribution_audit(pilot_aligned_rows, suites, checkpoint),
    )
    passes, reasons = preflight(control_audit, aligned_audit)
    summary: dict[str, Any] = {
        "schema": SCHEMA,
        "current_weights_sha256": sha256_file(weights),
        "runtime_profile": runtime_profile,
        "training_opening_corpus": corpus_manifest,
        "opening_depth_feasibility": feasibility,
        "orthogonal_classifications": ["opening_depth_structural_exhaustion_confirmed"],
        "pilot_replays": {
            "standard_start_control": pilot_control_manifest,
            "opening_seeded": pilot_aligned_manifest,
        },
        "pilot_distribution_audit": {
            "standard_start_control": control_audit,
            "opening_seeded": aligned_audit,
        },
        "stop_reasons": reasons,
    }
    if not passes:
        summary["classification"] = "distribution_alignment_preflight_failed"
    else:
        control_path, control_rows, control_manifest = generate_lane(
            lane="standard_start_control",
            workdir=workdir,
            checkpoint=checkpoint,
            corpus=None,
            target_rows=args.rows_per_lane,
            seed=args.seed,
            simulations=args.selfplay_simulations,
        )
        aligned_path, aligned_rows, aligned_manifest = generate_lane(
            lane="opening_seeded",
            workdir=workdir,
            checkpoint=checkpoint,
            corpus=corpus,
            target_rows=args.rows_per_lane,
            seed=args.seed,
            simulations=args.selfplay_simulations,
        )
        control_rows, aligned_rows = truncate_matched_whole_games(
            control_rows, aligned_rows, seed=args.seed
        )
        write_jsonl(control_path, control_rows)
        write_jsonl(aligned_path, aligned_rows)
        control_audit = distribution_audit(control_rows, suites, checkpoint)
        aligned_audit = distribution_audit(aligned_rows, suites, checkpoint)
        full_passes, full_reasons = preflight(control_audit, aligned_audit)
        summary["replays"] = {
            "standard_start_control": replay_manifest(
                control_rows,
                control_path,
                lane="standard_start_control",
                start_source="standard_initial_state",
                seed=args.seed,
            ),
            "opening_seeded": replay_manifest(
                aligned_rows,
                aligned_path,
                lane="opening_seeded",
                start_source="training_opening_corpus",
                seed=args.seed,
            ),
        }
        summary["full_distribution_audit"] = {
            "standard_start_control": control_audit,
            "opening_seeded": aligned_audit,
        }
        if not full_passes:
            summary["classification"] = "distribution_alignment_preflight_failed"
            summary["stop_reasons"].extend(full_reasons)
            write_json(workdir / "summary_metrics.json", summary)
            write_reports(summary)
            return 0
        # Immutable manifests and duplicate runs are deliberately only reachable after leakage/coverage validation.
        runs = {}
        for name, path, rows in (
            ("standard_start_joint_heads_e1", control_path, control_rows),
            ("opening_seeded_joint_heads_e1", aligned_path, aligned_rows),
        ):
            lane_dir = workdir / name
            audit_path = lane_dir / "replay_audit.json"
            write_json(
                audit_path,
                replay_manifest(
                    rows, path, lane=name, start_source=name, seed=args.seed
                ),
            )
            build_manifest(
                rows=rows,
                workdir=lane_dir,
                current=current,
                replay=path,
                replay_audit=audit_path,
                seed=args.seed,
                epochs=1,
                batch_size=512,
            )
            manifest_path = lane_dir / "training_manifest.json"
            device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
            run_prefix = "control" if name.startswith("standard") else "aligned"
            run_a, run_b = (
                train_fixed_manifest(manifest_path, device, f"{run_prefix}_run_a"),
                train_fixed_manifest(manifest_path, device, f"{run_prefix}_run_b"),
            )
            runs[name] = {
                "manifest": json.loads(manifest_path.read_text()),
                f"{run_prefix}_run_a": {
                    k: v for k, v in run_a.items() if not isinstance(v, np.ndarray)
                },
                f"{run_prefix}_run_b": {
                    k: v for k, v in run_b.items() if not isinstance(v, np.ndarray)
                },
                "reproducibility": compare_runs(run_a, run_b),
            }
        summary["training"] = runs
        if not all(run["reproducibility"]["passes"] for run in runs.values()):
            summary["classification"] = "full_scale_training_nondeterministic"
            summary["stop_reasons"].append("same_device_training_diverged")
        else:
            control_artifact = named_artifact_link(
                workdir,
                "standard_start_joint_heads_e1",
                Path(
                    runs["standard_start_joint_heads_e1"]["control_run_a"]["artifact"]
                ),
            )
            aligned_artifact = named_artifact_link(
                workdir,
                "opening_seeded_joint_heads_e1",
                Path(
                    runs["opening_seeded_joint_heads_e1"]["aligned_run_a"]["artifact"]
                ),
            )
            control_validation = [
                control_rows[index]
                for index in runs["standard_start_joint_heads_e1"]["manifest"][
                    "validation_source_row_indexes"
                ]
            ]
            aligned_validation = [
                aligned_rows[index]
                for index in runs["opening_seeded_joint_heads_e1"]["manifest"][
                    "validation_source_row_indexes"
                ]
            ]
            summary["cross_domain_replay_probes"] = {
                "standard_candidate_on_standard_validation": replay_probe(
                    candidate=control_artifact,
                    current=current,
                    rows=control_validation,
                    seed=args.seed,
                ),
                "standard_candidate_on_opening_seeded_validation": replay_probe(
                    candidate=control_artifact,
                    current=current,
                    rows=aligned_validation,
                    seed=args.seed,
                ),
                "aligned_candidate_on_opening_seeded_validation": replay_probe(
                    candidate=aligned_artifact,
                    current=current,
                    rows=aligned_validation,
                    seed=args.seed,
                ),
                "aligned_candidate_on_standard_validation": replay_probe(
                    candidate=aligned_artifact,
                    current=current,
                    rows=control_validation,
                    seed=args.seed,
                ),
            }
            summary["canonical_search_probes"] = {
                "standard": canonical_search_probe(
                    candidate=control_artifact,
                    current=current,
                    rows=control_rows,
                    seed=args.seed,
                    workers=args.workers,
                ),
                "aligned": canonical_search_probe(
                    candidate=aligned_artifact,
                    current=current,
                    rows=aligned_rows,
                    seed=args.seed,
                    workers=args.workers,
                ),
            }
            medium = paired_strength_screen(
                workdir=workdir / "medium",
                suite=Path(args.medium_suite),
                current=current,
                control=control_artifact,
                aligned=aligned_artifact,
                seed=args.seed,
                workers=args.workers,
            )
            summary["medium_strength"] = medium
            if not medium_strength_pass(medium):
                aligned_vs_control = medium["paired_opening_bootstrap_95"][
                    "aligned_minus_control"
                ]["384:256"]["mean"]
                summary["classification"] = (
                    "distribution_shift_not_primary_bottleneck"
                    if aligned_vs_control < 0.03
                    else "distribution_alignment_improves_learning_but_not_strength"
                )
                summary["stop_reasons"].append("medium_strength_gate_failed")
            else:
                fixed = paired_strength_screen(
                    workdir=workdir / "fixed_large",
                    suite=Path(args.fixed_large_suite),
                    current=current,
                    control=control_artifact,
                    aligned=aligned_artifact,
                    seed=args.seed,
                    workers=args.workers,
                )
                summary["fixed_large_strength"] = fixed
                fixed_current = fixed["paired_opening_bootstrap_95"][
                    "aligned_minus_current"
                ]
                fixed_pass = (
                    fixed_current["384:256"]["mean"] >= 0.05
                    and fixed_current["384:256"]["lower"] > 0.01
                    and fixed_current["768:768"]["mean"] >= -0.05
                    and fixed_current["1200:1200"]["mean"] >= -0.03
                    and fixed_current["1200:256"]["mean"] >= -0.03
                )
                if not fixed_pass:
                    summary["classification"] = (
                        "distribution_alignment_improves_learning_but_not_strength"
                    )
                    summary["stop_reasons"].append("fixed_large_qualification_failed")
                else:
                    summary["heldout_strength"] = {
                        path.name: paired_strength_screen(
                            workdir=workdir / f"heldout_{index}",
                            suite=path,
                            current=current,
                            control=control_artifact,
                            aligned=aligned_artifact,
                            seed=args.seed,
                            workers=args.workers,
                        )
                        for index, path in enumerate(heldout)
                    }
                    heldout_pass, heldout_qualification = heldout_qualification_pass(
                        summary["heldout_strength"]
                    )
                    summary["heldout_qualification"] = heldout_qualification
                    if heldout_pass:
                        summary["classification"] = (
                            "distribution_aligned_joint_heads_candidate"
                        )
                        summary["stop_reasons"].append("promotion_not_run_by_protocol")
                    else:
                        summary["classification"] = (
                            "distribution_alignment_improves_learning_but_not_strength"
                        )
                        summary["stop_reasons"].append("heldout_qualification_failed")
    write_json(workdir / "summary_metrics.json", summary)
    write_reports(summary)
    print(
        json.dumps(
            {"classification": summary["classification"], "workdir": str(workdir)}
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
